
services:
  web:
    build: .
    ports:
      - "8888:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
    # حذف volume تا image جدید جایگزین بشه

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
