name: Build and Test with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        docker compose --version

    - name: Build and run services
      run: |
        docker compose up -d --build

    - name: Wait for services to be ready
      run: sleep 15

    - name: Run tests inside container
      run: |
        docker compose exec -T web pytest app/tests/
