name: Build and Test with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build and run services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to become healthy..."
          sleep 15  # یا ابزار healthcheck دقیق‌تر استفاده کن اگر تنظیمش کردی در docker-compose.yml

      - name: Run tests inside container
        run: |
          docker compose exec -T web pytest app/tests/
