name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH with detailed logs
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -x   # فعال کردن حالت debug
            whoami
            pwd
            ls -l
            cd /home/smile/my_projects/todo-app
            git pull origin main
            docker compose build --no-cache
            docker compose up -d --remove-orphans
            docker ps
            exit
          EOF
